### ISSUE TITLE
créer une navbar avec une logique de connect

### ISSUE THREAD

**Issue by vvenance** [Astoo/rails-airbnb-clone#83]

**Comment by Astoo** [comment]
Pour mettre la photo de profil Facebook automatiquement : 

<% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
<%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

**Comment by Astoo** [comment]
Lorsque ce sera bon, pour mettre en production, faire dans le shell  : 
figaro heroku:set -e production
